<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Neap.Services</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Neap.Core.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Neap.Core\Neap.Core.csproj" />
  </ItemGroup>
</Project>
