<Project>
  <PropertyGroup>
    <Product>Neap</Product>
    <Company>lykosapps</Company>
    <Authors>lykosapps</Authors>
    <Copyright>Copyright (c) 2026 lykosapps</Copyright>
    <PackageLicenseExpression>GPL-3.0-or-later</PackageLicenseExpression>
    <Version>0.1.0</Version>
  </PropertyGroup>

  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
</Project>
